modLoader="javafml"
loaderVersion="[4.0.44]"
license="AGPL-3.0-only"

[[mods]]
modId="ae2federation"
version="${mod_version}"
displayName="AE2 Federation"
authors="ControlNet"
description='''
Connect independent AE2 networks to share storage, autocrafting, processing, and ME power.
'''

[[mixins]]
config="ae2federation.mixins.json"

[[dependencies.ae2federation]]
modId="neoforge"
type="required"
versionRange="[21.1.250]"
ordering="NONE"
side="BOTH"

[[dependencies.ae2federation]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.ae2federation]]
modId="ae2"
type="required"
versionRange="[19.2.17]"
ordering="AFTER"
side="BOTH"

[[dependencies.ae2federation]]
modId="ldlib2"
type="required"
versionRange="[2.2.34]"
ordering="AFTER"
side="BOTH"
